SELECT
    HOUR(ao.DATETIME) as 'HOUR',
    COUNT(ao.ANIMAL_ID) AS 'COUNT'
FROM
    ANIMAL_OUTS ao
WHERE
    HOUR(ao.DATETIME) BETWEEN 9 AND 19
GROUP BY
    DATE_FORMAT(ao.DATETIME, '%H')
ORDER BY
    HOUR(ao.DATETIME) ASC;