SELECT
    SUM(hg.SCORE) AS 'SCORE', he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
FROM
    HR_DEPARTMENT hd
RIGHT JOIN
    HR_EMPLOYEES he ON hd.DEPT_ID = he.DEPT_ID
RIGHT JOIN 
    HR_GRADE hg ON he.EMP_NO = hg.EMP_NO
WHERE
    hg.YEAR = 2022
GROUP BY
    he.EMP_NO
ORDER BY
    SUM(hg.SCORE) DESC
LIMIT 1;
